
services:
  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremiomcp
    ports:
      - "9047:9047"     # Web UI
      - "31010:31010"   # JDBC/ODBC
      - "32010:32010"   # Arrow Flight
      - "45678:45678"   # Internal
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist
    volumes:
      - dremio-data-volume:/opt/dremio/data
  
  # Sample Data - Comment out if needed
  pgcrm:
    image: postgres:15
    environment:
      - POSTGRES_DB=crm
      - POSTGRES_USER=crm
      - POSTGRES_PASSWORD=crm_pw
    volumes:
      - ./init/pgcrm:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Sample Data - comment out if needed
  mysqlbill:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=billing
      - MYSQL_USER=billing
      - MYSQL_PASSWORD=billing_pw
      - MYSQL_ROOT_PASSWORD=root_pw
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

volumes:
  dremio-data-volume:
